### PR TITLE
Update to PostCSS 5.x

### PR DESCRIPTION
**Pull request by timdorr**

### CODE REVIEW

**Comment by vn38minhtran** [comment]
+1

**Comment by jedmao** [comment]
See https://github.com/webpack/css-loader/issues/135
@timdorr it looks like this one needs a rebase?

**Comment by timdorr** [comment]
Yeah, I'll merge in the changes from master. 

BTW, never rebase on a branch you've pushed to others. The commit SHAs change, so things like Github line comments and other stuff gets screwed up. Been bit by that before! :wink:

**Comment by jedmao** [comment]
@timdorr GitHub used to have issues w/ comments on outdated diffs, but they've since fixed that. We rebase all the time and outdated diffs end up looking like this:

image

There might still be issues when commenting directly on a commit, but we tend to avoid doing that anyway, for the very reason you pointed out; though, they might have fixed that recently as well.

On this PR, however, there have been no line comments, it's very small, and you would benefit from doing a rebase for a clean merge.

**Comment by jedmao** [comment]
@timdorr I just confirmed that commit comments are, in fact, wiped out. This is why you should try your best to comment on the "Files changed" diff/tab until GitHub finds a magical solution for that too.

Again though, this PR has no commit comments, so it's irrelevant here.

**Comment by sokra** [comment]
Thanks

**Comment by jedmao** [comment]
@sokra are you going to publish a new major version on npm soon?

**Comment by geelen** [comment]
New version will land this week in the big `1.0` release

**Pull request merged**
